# Generated by Django 4.2.1 on 2023-05-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_elevation', models.CharField(choices=[('P', '00-00'), ('C', '00-00'), ('D', '00-00')], default='P', max_length=1)),
                ('soil_type', models.CharField(choices=[('P', '00-00'), ('C', '00-00'), ('D', '00-00')], default='P', max_length=1)),
                ('rainfall_pattern', models.CharField(choices=[('P', '00-00'), ('C', '00-00'), ('D', '00-00')], default='P', max_length=1)),
                ('other_crops', models.CharField(max_length=50, null=True)),
                ('intercrop', models.CharField(max_length=50, null=True)),
                ('pure_stand', models.CharField(max_length=50, null=True)),
                ('norm_land', models.CharField(max_length=50, null=True)),
                ('seas_land', models.CharField(max_length=50, null=True)),
                ('aban_land', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Land_tenurship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=50, null=True)),
                ('family', models.CharField(max_length=50, null=True)),
                ('lease', models.CharField(max_length=100, null=True)),
                ('caretaker', models.CharField(max_length=50, null=True)),
                ('agent', models.CharField(max_length=50, null=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_access', models.CharField(max_length=50, null=True)),
                ('land_slide', models.CharField(max_length=50, null=True)),
                ('flooding', models.CharField(max_length=50, null=True)),
                ('heavy_metalsa', models.CharField(max_length=50, null=True)),
                ('chemical_spills', models.CharField(max_length=50, null=True)),
                ('dumping', models.CharField(max_length=50, null=True)),
                ('feedlot', models.CharField(max_length=50, null=True)),
                ('pesticides', models.CharField(max_length=50, null=True)),
                ('septic_tanks', models.CharField(max_length=50, null=True)),
                ('manical', models.CharField(choices=[('P', 'Was this water source is used?'), ('C', 'Yes'), ('D', 'No')], default='P', max_length=1)),
                ('river', models.CharField(choices=[('P', 'Was this water source is used?'), ('C', 'Yes'), ('D', 'No')], default='P', max_length=1)),
                ('spring', models.CharField(choices=[('P', 'Was this water source is used?'), ('C', 'Yes'), ('D', 'No')], default='P', max_length=1)),
                ('well', models.CharField(choices=[('P', 'Was this water source is used?'), ('C', 'Yes'), ('D', 'No')], default='P', max_length=1)),
                ('harvested', models.CharField(choices=[('P', 'Was this water source is used?'), ('C', 'Yes'), ('D', 'No')], default='P', max_length=1)),
                ('treated', models.CharField(choices=[('P', 'Select'), ('C', 'Yes'), ('D', 'No')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='symmary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_production', models.CharField(max_length=50, null=True)),
                ('peak_productions', models.CharField(max_length=50, null=True)),
                ('inspected_by', models.DateTimeField(verbose_name='Inspetion Date')),
                ('date', models.DateTimeField(verbose_name='Current Date')),
            ],
        ),
        migrations.CreateModel(
            name='tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tree_types', models.CharField(max_length=50, null=True)),
                ('Mature_trees', models.IntegerField()),
                ('Bearing_trees', models.IntegerField()),
                ('NonBearing_trees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_ID', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('village', models.CharField(max_length=50, null=True)),
                ('parish', models.CharField(max_length=50, null=True)),
                ('GPS_location', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('age', models.CharField(choices=[('A', '18-25'), ('B', '26-35'), ('C', '36-60'), ('D', '61+')], default='A', max_length=1)),
            ],
        ),
    ]
