# Generated by Django 4.2.1 on 2023-05-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0002_rename_heavy_metalsa_state_heavy_metals'),
    ]

    operations = [
        migrations.CreateModel(
            name='fullform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_ID', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('village', models.CharField(max_length=50, null=True)),
                ('parish', models.CharField(max_length=50, null=True)),
                ('GPS_location', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('age', models.CharField(choices=[('A', '18-25'), ('B', '26-35'), ('C', '36-60'), ('D', '61+')], default='A', max_length=1)),
                ('titles', models.CharField(max_length=50, null=True)),
                ('family', models.CharField(max_length=50, null=True)),
                ('lease', models.CharField(max_length=100, null=True)),
                ('caretaker', models.CharField(max_length=50, null=True)),
                ('agent', models.CharField(max_length=50, null=True)),
                ('comments', models.TextField(blank=True)),
                ('Tree_types', models.CharField(max_length=50, null=True)),
                ('Mature_trees', models.IntegerField()),
                ('Bearing_trees', models.IntegerField()),
                ('NonBearing_trees', models.IntegerField()),
                ('land_elevation', models.CharField(choices=[('P', '00-00'), ('C', '00-00'), ('D', '00-00')], default='P', max_length=1)),
                ('soil_type', models.CharField(choices=[('P', '00-00'), ('C', '00-00'), ('D', '00-00')], default='P', max_length=1)),
                ('rainfall_pattern', models.CharField(choices=[('P', '00-00'), ('C', '00-00'), ('D', '00-00')], default='P', max_length=1)),
                ('other_crops', models.CharField(max_length=50, null=True)),
                ('intercrop', models.CharField(max_length=50, null=True)),
                ('pure_stand', models.CharField(max_length=50, null=True)),
                ('norm_land', models.CharField(max_length=50, null=True)),
                ('seas_land', models.CharField(max_length=50, null=True)),
                ('aban_land', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='annual_production',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='date2',
            field=models.DateTimeField(null=True, verbose_name='Current Date'),
        ),
        migrations.AddField(
            model_name='state',
            name='inspected_by2',
            field=models.DateTimeField(null=True, verbose_name='Inspetion Date'),
        ),
        migrations.AddField(
            model_name='state',
            name='peak_productions',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='symmary',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Current Date'),
        ),
        migrations.AlterField(
            model_name='symmary',
            name='inspected_by',
            field=models.DateTimeField(null=True, verbose_name='Inspetion Date'),
        ),
    ]
