# Generated by Django 4.2.1 on 2023-05-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0003_fullform_state_annual_production_state_date2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='annual_production',
        ),
        migrations.RemoveField(
            model_name='state',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='state',
            name='inspected_by2',
        ),
        migrations.RemoveField(
            model_name='state',
            name='peak_productions',
        ),
        migrations.AddField(
            model_name='fullform',
            name='annual_production',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fullform',
            name='chemical_spills',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fullform',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Current Date'),
        ),
        migrations.AddField(
            model_name='fullform',
            name='dumping',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fullform',
            name='feedlot',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fullform',
            name='flooding',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fullform',
            name='harvested',
            field=models.CharField(choices=[('P', 'Was this water source is used?'), ('C', 'Yes'), ('D', 'No')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='fullform',
            name='heavy_metals',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fullform',
            name='inspected_by',
            field=models.DateTimeField(null=True, verbose_name='Inspetion Date'),
        ),
        migrations.AddField(
            model_name='fullform',
            name='land_slide',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fullform',
            name='manical',
            field=models.CharField(choices=[('P', 'Was this water source is used?'), ('C', 'Yes'), ('D', 'No')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='fullform',
            name='peak_productions',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fullform',
            name='pesticides',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fullform',
            name='river',
            field=models.CharField(choices=[('P', 'Was this water source is used?'), ('C', 'Yes'), ('D', 'No')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='fullform',
            name='road_access',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fullform',
            name='septic_tanks',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fullform',
            name='spring',
            field=models.CharField(choices=[('P', 'Was this water source is used?'), ('C', 'Yes'), ('D', 'No')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='fullform',
            name='treated',
            field=models.CharField(choices=[('P', 'Select'), ('C', 'Yes'), ('D', 'No')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='fullform',
            name='well',
            field=models.CharField(choices=[('P', 'Was this water source is used?'), ('C', 'Yes'), ('D', 'No')], default='P', max_length=1),
        ),
    ]
