# Generated by Django 4.2.1 on 2023-05-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0006_alter_fullform_tree_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullform',
            name='Tree_types',
            field=models.CharField(choices=[('A', 'Select'), ('P', 'Nutmeg'), ('C', 'Coconut')], default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Current Date'),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='inspected_by',
            field=models.DateTimeField(null=True, verbose_name='Inspetion Date'),
        ),
    ]
