# Generated by Django 4.2.1 on 2023-05-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0007_alter_fullform_tree_types_alter_fullform_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullform',
            name='date',
            field=models.DateField(null=True, verbose_name='Current Date'),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='inspected_by',
            field=models.DateField(null=True, verbose_name='Inspection Date'),
        ),
    ]
