# Generated by Django 4.2.1 on 2023-05-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0009_crops_remove_fullform_other_crops_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crops',
            new_name='crop',
        ),
    ]
