# Generated by Django 4.2.1 on 2023-05-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0010_rename_crops_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullform',
            name='Bearing_trees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='Mature_trees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='NonBearing_trees',
            field=models.IntegerField(default=0),
        ),
    ]
