# Generated by Django 4.2.1 on 2023-05-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0011_alter_fullform_bearing_trees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullform',
            name='Tree_types',
            field=models.CharField(choices=[('', 'Select'), ('Nutmeg', 'Nutmeg'), ('Coconut', 'Coconut')], default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='harvested',
            field=models.CharField(choices=[('', 'Was this water source is used?'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='land_elevation',
            field=models.CharField(choices=[('', 'Select'), ('Low Belt', 'Low Belt'), ('Middle Belt', 'Middle Belt'), ('High Belt', 'High Belt')], default='P', max_length=100),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='manical',
            field=models.CharField(choices=[('', 'Was this water source is used?'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='rainfall_pattern',
            field=models.CharField(choices=[('', 'Select'), ('Persistent', 'Persistent'), ('Occasional', 'Occasional'), ('Mild', 'Mild')], default='P', max_length=100),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='river',
            field=models.CharField(choices=[('', 'Was this water source is used?'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='soil_type',
            field=models.CharField(choices=[('', 'Select'), ('Sandy Soil', 'Sandy Soil'), ('Clay Soil', 'Clay Soil'), ('Stilt Soil', 'Stilt Soil'), ('Peat Soil', 'Peat Soil'), ('Chalk Soil', 'Chalk Soil'), ('Loamy Soil', 'Loamy Soil'), ('Clay Loam Soil', 'Clay Loam Soil'), ('Sandy Loam Soil', 'Sandy Loam Soil')], default='P', max_length=100),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='spring',
            field=models.CharField(choices=[('', 'Was this water source is used?'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='treated',
            field=models.CharField(choices=[('', 'Select'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='well',
            field=models.CharField(choices=[('', 'Was this water source is used?'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1),
        ),
    ]
