# Generated by Django 4.2.1 on 2023-05-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0012_alter_fullform_tree_types_alter_fullform_harvested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moisture_Analysis_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE_OF_SAMPLING', models.DateField(null=True, verbose_name='Current Date')),
                ('STATION', models.CharField(max_length=50, null=True)),
                ('BATCH_CODE', models.IntegerField(default=0)),
                ('Quantity_of_Bags', models.IntegerField(default=0)),
                ('Quantity_of_Sample', models.IntegerField(default=0)),
                ('Total_Weight', models.FloatField(default=0)),
                ('Initial_Sample_Weight', models.FloatField(default=0)),
                ('Insect_Damaged', models.FloatField(default=0)),
                ('Broken', models.FloatField(default=0)),
                ('Mould', models.FloatField(default=0)),
                ('Final_Sample_Weight', models.FloatField(default=0)),
                ('READING_1', models.CharField(max_length=50, null=True)),
                ('READING_2', models.CharField(max_length=50, null=True)),
                ('READING_3', models.CharField(max_length=50, null=True)),
                ('AVERAGE', models.CharField(max_length=50, null=True)),
                ('DECISION', models.CharField(max_length=50, null=True)),
                ('Comments', models.TextField(blank=True)),
                ('TEST_PERFORMED_BY', models.CharField(max_length=50, null=True)),
                ('SIGNED_BY', models.CharField(max_length=50, null=True)),
                ('DATE_OF_REPORT', models.DateField(null=True, verbose_name='Current Date')),
                ('SIGNED_BY_QUALITY_ASSURANCE_OFFICER', models.CharField(max_length=50, null=True)),
                ('DATE', models.DateField(null=True, verbose_name='Current Date')),
            ],
        ),
        migrations.CreateModel(
            name='Moisture_Analysis_B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE_OF_SAMPLING', models.DateField(null=True, verbose_name='Current Date')),
                ('STATION', models.CharField(max_length=50, null=True)),
                ('BATCH_CODE', models.IntegerField(default=0)),
                ('Total_Quantity_of_Bags_in_Non_Compliance', models.IntegerField(default=0)),
                ('Total_Weight_of_Nutmeg_in_Non_Compliance', models.IntegerField(default=0)),
                ('Additional_Drying_Period', models.CharField(max_length=50, null=True)),
                ('Initial_Sample_Weight', models.FloatField(default=0)),
                ('Insect_Damaged', models.FloatField(default=0)),
                ('Broken', models.FloatField(default=0)),
                ('Mould', models.FloatField(default=0)),
                ('Final_Sample_Weight', models.FloatField(default=0)),
                ('READING_1', models.CharField(max_length=50, null=True)),
                ('READING_2', models.CharField(max_length=50, null=True)),
                ('READING_3', models.CharField(max_length=50, null=True)),
                ('AVERAGE', models.CharField(max_length=50, null=True)),
                ('DECISION', models.CharField(max_length=50, null=True)),
                ('Comments', models.TextField(blank=True)),
                ('TEST_PERFORMED_BY', models.CharField(max_length=50, null=True)),
                ('SIGNED_BY', models.CharField(max_length=50, null=True)),
                ('DATE_OF_REPORT', models.DateField(null=True, verbose_name='Current Date')),
                ('SIGNED_BY_QUALITY_ASSURANCE_OFFICER', models.CharField(max_length=50, null=True)),
                ('DATE', models.DateField(null=True, verbose_name='Current Date')),
            ],
        ),
    ]
