# Generated by Django 4.2.1 on 2023-05-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0014_dried_moisture_analysis_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quality_control',
            old_name='DATE',
            new_name='DATE_1',
        ),
        migrations.AddField(
            model_name='quality_control',
            name='DATE_2',
            field=models.DateField(null=True, verbose_name='Current Date'),
        ),
    ]
