# Generated by Django 4.2.1 on 2023-05-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0015_rename_date_quality_control_date_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='DATE_OF_REPORT',
            field=models.DateField(null=True, verbose_name='Date of Report'),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='DATE_OF_SAMPLING',
            field=models.DateField(null=True, verbose_name='Date of Sampling'),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='DATE_OF_REPORT',
            field=models.DateField(null=True, verbose_name='Date of Report'),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='DATE_OF_SAMPLING',
            field=models.DateField(null=True, verbose_name='Date of Sampling'),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='DATE_OF_REPORT',
            field=models.DateField(null=True, verbose_name='Date of Report'),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='DATE_OF_SAMPLING_H',
            field=models.DateField(null=True, verbose_name='Date of Heavy Sampling'),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='DATE_OF_SAMPLING_L',
            field=models.DateField(null=True, verbose_name='Date of Light Sampling'),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_b',
            name='DATE',
            field=models.DateField(null=True, verbose_name='Signed On'),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_b',
            name='DATE_OF_REPORT',
            field=models.DateField(null=True, verbose_name='Date of Report'),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_b',
            name='DATE_OF_SAMPLING_H',
            field=models.DateField(null=True, verbose_name='Date of Heavy Sampling'),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_b',
            name='DATE_OF_SAMPLING_L',
            field=models.DateField(null=True, verbose_name='Date of Light Sampling'),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='DATE_2',
            field=models.DateField(null=True, verbose_name='Signed On'),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='DATE_OF_REPORT',
            field=models.DateField(null=True, verbose_name='Date of Report'),
        ),
    ]
