  # Generated by Django 4.2.1 on 2023-06-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0017_alter_dried_moisture_analysis_a_final_sample_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floated_moisture_analysis_b',
            name='Initial_Sample_Weight_H',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='floated_moisture_analysis_b',
            name='Initial_Sample_Weight_L',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='AVERAGE_H',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='AVERAGE_L',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='Final_Sample_Weight_H',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='Final_Sample_Weight_L',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
    ]
