# Generated by Django 4.2.1 on 2023-06-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0018_floated_moisture_analysis_b_initial_sample_weight_h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality_control',
            name='DATE_OF_REPORT',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
