# Generated by Django 4.2.1 on 2023-06-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0019_alter_quality_control_date_of_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality_control',
            name='DATE_OF_REPORT',
            field=models.DateField(null=True, verbose_name='Date of Report'),
        ),
    ]
