# Generated by Django 4.2.1 on 2023-06-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0020_alter_quality_control_date_of_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farmer_ID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='land_tenurship',
            name='farmer_ID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='farmer_ID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='symmary',
            name='farmer_ID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='farmer_ID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='land_elevation',
            field=models.CharField(choices=[('', 'Select'), ('Low Belt', 'Low Belt'), ('Middle Belt', 'Middle Belt'), ('High Belt', 'High Belt')], default='P', max_length=100),
        ),
        migrations.RemoveField(
            model_name='farm',
            name='other_crops',
        ),
        migrations.AlterField(
            model_name='farm',
            name='rainfall_pattern',
            field=models.CharField(choices=[('', 'Select'), ('Persistent', 'Persistent'), ('Occasional', 'Occasional'), ('Mild', 'Mild')], default='P', max_length=100),
        ),
        migrations.AlterField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(choices=[('', 'Select'), ('Sandy Soil', 'Sandy Soil'), ('Clay Soil', 'Clay Soil'), ('Stilt Soil', 'Stilt Soil'), ('Peat Soil', 'Peat Soil'), ('Chalk Soil', 'Chalk Soil'), ('Loamy Soil', 'Loamy Soil'), ('Clay Loam Soil', 'Clay Loam Soil'), ('Sandy Loam Soil', 'Sandy Loam Soil')], default='P', max_length=100),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='Initial_Sample_Weight_H',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='Initial_Sample_Weight_L',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='DATE_1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='DATE_2',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='DATE_OF_REPORT',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='harvested',
            field=models.CharField(choices=[('', 'Was this water source is used?'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='state',
            name='manical',
            field=models.CharField(choices=[('', 'Was this water source is used?'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='state',
            name='river',
            field=models.CharField(choices=[('', 'Was this water source is used?'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='state',
            name='spring',
            field=models.CharField(choices=[('', 'Was this water source is used?'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='state',
            name='treated',
            field=models.CharField(choices=[('', 'Select'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='state',
            name='well',
            field=models.CharField(choices=[('', 'Was this water source is used?'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='symmary',
            name='date',
            field=models.DateField(null=True, verbose_name='Current Date'),
        ),
        migrations.AlterField(
            model_name='symmary',
            name='inspected_by',
            field=models.DateField(null=True, verbose_name='Inspection Date'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='Bearing_trees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tree',
            name='Mature_trees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tree',
            name='NonBearing_trees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tree',
            name='Tree_types',
            field=models.CharField(choices=[('', 'Select'), ('Nutmeg', 'Nutmeg'), ('Coconut', 'Coconut')], default='A', max_length=50),
        ),
        migrations.AddField(
            model_name='farm',
            name='other_crops',
            field=models.ManyToManyField(to='gcna_data.crop'),
        ),
    ]
