# Generated by Django 4.2.1 on 2023-06-06 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0021_farm_farmer_id_land_tenurship_farmer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farmer_ID',
        ),
        migrations.RemoveField(
            model_name='state',
            name='farmer_ID',
        ),
        migrations.RemoveField(
            model_name='symmary',
            name='farmer_ID',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='farmer_ID',
        ),
        migrations.AlterField(
            model_name='land_tenurship',
            name='farmer_ID',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='gcna_data.user_info'),
        ),
        migrations.AlterField(
            model_name='land_tenurship',
            name='titles',
            field=models.CharField(choices=[('', 'Select'), ('Owned', 'Owned'), ('Freehold', 'Freehold'), ('Leased', 'Leased'), ('Family Land', 'Family Land'), ('ShareCrop', 'ShareCrop'), ('Rent', 'Rent'), ('Rented free', 'Rented free'), ('Premission to work land', 'Premission to work land'), ('Squatted', 'Squatted'), ('Government Land', 'Government Land'), ('Other', 'Other'), ('Caretaker', 'Caretaker'), ('Administrator', 'Administrator')], max_length=50, null=True),
        ),
    ]
