# Generated by Django 4.2.1 on 2023-06-06 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0022_remove_farm_farmer_id_remove_state_farmer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land_tenurship',
            name='farmer_ID',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='gcna_data.user_info', to_field='farmer_ID'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='farmer_ID',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
