# Generated by Django 4.2.1 on 2023-06-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0024_rename_titles_land_tenurship_tenure_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='GPS_location',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='email',
        ),
        migrations.AddField(
            model_name='user_info',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='user_info',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
