# Generated by Django 4.2.1 on 2023-06-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0025_remove_user_info_gps_location_remove_user_info_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
