# Generated by Django 4.2.1 on 2023-06-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0029_inspector_symmary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_info',
            name='Nutmeg_ID_No',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
