# Generated by Django 4.2.1 on 2023-06-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0030_alter_farmer_info_nutmeg_id_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer_info',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='land_info',
            name='farmer_ID',
        ),
        migrations.AddField(
            model_name='land_info',
            name='Nutmeg_ID_No',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='gcna_data.farmer_info', to_field='Nutmeg_ID_No'),
        ),
        migrations.AlterField(
            model_name='farmer_info',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
