# Generated by Django 4.2.1 on 2023-06-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0032_remove_nutmeg_frequency_never_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='Cultivation_Lemon',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the Lemon cultivation'),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='Cultivation_Lime',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the Lime cultivation'),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='Cultivation_Mangoes',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the Mangoes cultivation'),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='Estimated_Productiom_Lemon',
            field=models.IntegerField(default=0, verbose_name='What is the estimated production of Lemon'),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='Estimated_Productiom_Lime',
            field=models.IntegerField(default=0, verbose_name='What is the estimated production of Lime'),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='Estimated_Productiom_Mangoes',
            field=models.IntegerField(default=0, verbose_name='What is the estimated production of Mangoes'),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='No_of_Bearing_Trees_Lemon',
            field=models.IntegerField(default=0, verbose_name='What is the number of Bearing trees for Lemon'),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='No_of_Bearing_Trees_Lime',
            field=models.IntegerField(default=0, verbose_name='What is the number of Bearing trees for Lime'),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='No_of_Bearing_Trees_Mangoes',
            field=models.IntegerField(default=0, verbose_name='What is the number of Bearing trees for Mangoes'),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='No_of_Non_Bearing_Trees_Lemon',
            field=models.IntegerField(default=0, verbose_name='What is the number of Non-Bearing trees for Lemon'),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='No_of_Non_Bearing_Trees_Lime',
            field=models.IntegerField(default=0, verbose_name='What is the number of Non-Bearing trees for Lime'),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='No_of_Non_Bearing_Trees_Mangoes',
            field=models.IntegerField(default=0, verbose_name='What is the number of Non-Bearing trees for Mangoes'),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='Presence_of_Disease_Lemon',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Lemon'),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='Presence_of_Disease_Lime',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Lime'),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='Presence_of_Disease_Mangoes',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Mangoes'),
        ),
        migrations.AlterField(
            model_name='coconut_trees',
            name='Cultivation_Atlantic_Tall',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the Atlantic Tall Tree cultivation'),
        ),
        migrations.AlterField(
            model_name='coconut_trees',
            name='Cultivation_Dwarf',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the Dwarf Tree cultivation'),
        ),
        migrations.AlterField(
            model_name='coconut_trees',
            name='End_Use_Atlantic_Tall',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the intended end use if the Atlantic Tall Tree'),
        ),
        migrations.AlterField(
            model_name='coconut_trees',
            name='End_Use_Dwarf',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the intended end use of the Dwarf Tree'),
        ),
        migrations.AlterField(
            model_name='coconut_trees',
            name='Estimated_Productiom_Atlantic_Tall',
            field=models.IntegerField(default=0, verbose_name='What is the estimated production of Atlantic Tall Trees'),
        ),
        migrations.AlterField(
            model_name='coconut_trees',
            name='Estimated_Productiom_Dwarf',
            field=models.IntegerField(default=0, verbose_name='What is the estimated production of Dwarf Trees'),
        ),
        migrations.AlterField(
            model_name='coconut_trees',
            name='No_of_Bearing_Trees_Atlantic_Tall',
            field=models.IntegerField(default=0, verbose_name='What is the number of Bearing trees for Atlantic Tall Trees'),
        ),
        migrations.AlterField(
            model_name='coconut_trees',
            name='No_of_Bearing_Trees_Dwarf',
            field=models.IntegerField(default=0, verbose_name='What is the number of Bearing trees for Dwarf Trees'),
        ),
        migrations.AlterField(
            model_name='coconut_trees',
            name='No_of_Non_Bearing_Trees_Atlantic_Tall',
            field=models.IntegerField(default=0, verbose_name='What is the number of Non-Bearing trees for Atlantic Tall Trees'),
        ),
        migrations.AlterField(
            model_name='coconut_trees',
            name='No_of_Non_Bearing_Trees_Dwarf',
            field=models.IntegerField(default=0, verbose_name='What is the number of Non-Bearing Dwarf Trees'),
        ),
        migrations.AlterField(
            model_name='coconut_trees',
            name='Presence_of_Disease_Atlantic_Tall',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Atlantic Tall Trees'),
        ),
        migrations.AlterField(
            model_name='coconut_trees',
            name='Presence_of_Disease_Dwarf',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Dwarf Trees'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='Weeds',
            field=models.CharField(choices=[('', 'Select'), ('Y', 'Good'), ('N', 'Fair'), ('N', 'Poor')], default='P', max_length=1, verbose_name='What is the state of the weeds?'),
        ),
        migrations.AlterField(
            model_name='nutmeg_trees',
            name='Bearing_trees_16_24_years',
            field=models.IntegerField(default=0, verbose_name='Estimated production Bearing trees between 16 to 24'),
        ),
        migrations.AlterField(
            model_name='nutmeg_trees',
            name='Bearing_trees_16_24_years_quantity',
            field=models.IntegerField(default=0, verbose_name='Number of Bearing trees between 16 to 24'),
        ),
        migrations.AlterField(
            model_name='nutmeg_trees',
            name='Bearing_trees_6_15_years_estimated_production',
            field=models.IntegerField(default=0, verbose_name='Estimated production Bearing trees between 6 to 14'),
        ),
        migrations.AlterField(
            model_name='nutmeg_trees',
            name='Bearing_trees_6_15_years_quantity',
            field=models.IntegerField(default=0, verbose_name='Number of Bearing trees between 6 to 14'),
        ),
        migrations.AlterField(
            model_name='nutmeg_trees',
            name='Estimated_peak_period',
            field=models.IntegerField(default=0, verbose_name='What is the estimated peak period?'),
        ),
        migrations.AlterField(
            model_name='nutmeg_trees',
            name='Mature_trees_25_years_estimated_production',
            field=models.IntegerField(default=0, verbose_name='Estimated production for Mature older than 25 years'),
        ),
        migrations.AlterField(
            model_name='nutmeg_trees',
            name='Mature_trees_25_years_quantity',
            field=models.IntegerField(default=0, verbose_name='Number of Mature trees older than 25 years'),
        ),
        migrations.AlterField(
            model_name='nutmeg_trees',
            name='Non_Bearing_trees_5_years_estimated_production',
            field=models.IntegerField(default=0, verbose_name='Estimated production for Non-bearing trees younger than 5 years'),
        ),
        migrations.AlterField(
            model_name='nutmeg_trees',
            name='Non_Bearing_trees_5_years_quantity',
            field=models.IntegerField(default=0, verbose_name='Number of Non-Bearing trees younger than 5 years'),
        ),
        migrations.AlterField(
            model_name='nutmeg_variety',
            name='Banda',
            field=models.CharField(max_length=50, null=True, verbose_name='Is the Banda nutmeg present?'),
        ),
        migrations.AlterField(
            model_name='nutmeg_variety',
            name='Malayan_Indonesia',
            field=models.CharField(max_length=50, null=True, verbose_name='Is the Malayan Indonesia nutmeg present?'),
        ),
        migrations.AlterField(
            model_name='nutmeg_variety',
            name='Papua',
            field=models.CharField(max_length=50, null=True, verbose_name='Is the Papua nutmeg present?'),
        ),
        migrations.AlterField(
            model_name='nutmeg_variety',
            name='dominant_Variety',
            field=models.CharField(max_length=50, null=True, verbose_name='What nutmeg type is the most common?'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Cultivation_Celery',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the celery cultivation'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Cultivation_Hot_Pepper',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the hot pepper cultivation'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Cultivation_Parsley',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the parsley cultivation'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Cultivation_Petit_Bum',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the pwtit bum cultivation'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Cultivation_Seasoning_Pepper',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the seasoning pepper cultivation'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Cultivation_Thyme',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the THYME cultivation'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Cultivation_chive',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the chive cultivation'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='No_of_Stools_Celery',
            field=models.IntegerField(default=0, verbose_name='What is the number of stools  for Celery'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='No_of_Stools_Hot_Pepper',
            field=models.IntegerField(default=0, verbose_name='What is the number of stools for Hot pepper'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='No_of_Stools_Parsley',
            field=models.IntegerField(default=0, verbose_name='What is the number of stools for Parsley'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='No_of_Stools_Petit_Bum',
            field=models.IntegerField(default=0, verbose_name='What is the number of stools  for Petit Bum'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='No_of_Stools_Seasoning_Pepper',
            field=models.IntegerField(default=0, verbose_name='What is the number of stools  for Seasoning pepper'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='No_of_Stools_Thyme',
            field=models.IntegerField(default=0, verbose_name='What is the number of stools  for Thyme'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='No_of_Stools_chive',
            field=models.IntegerField(default=0, verbose_name='What is the number of stools  for chive'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Presence_of_Disease_Celery',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Celery'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Presence_of_Disease_Hot_Pepper',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Hot pepper'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Presence_of_Disease_Parsley',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Parsley'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Presence_of_Disease_Petit_Bum',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Petit Bum '),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Presence_of_Disease_Seasoning_Pepper',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Seasoning pepper'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Presence_of_Disease_Thyme',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Thyme'),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Presence_of_Disease_chive',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for chive'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Cultivation_Bayleaf',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the Bayleaf cultivation'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Cultivation_Cinnamon',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the Cinnamon cultivation'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Cultivation_Clove',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the Clove cultivation'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Cultivation_Ginger',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the Ginger cultivation'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Cultivation_Tumeric',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the Tumeric cultivation'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Estimated_Productiom_Bayleaf',
            field=models.IntegerField(default=0, verbose_name='What is the estimated production of Bayleaf'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Estimated_Productiom_Cinnamon',
            field=models.IntegerField(default=0, verbose_name='What is the estimated production of Cinnamon'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Estimated_Productiom_Clove',
            field=models.IntegerField(default=0, verbose_name='What is the estimated production of clove'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Estimated_Productiom_Ginger',
            field=models.IntegerField(default=0, verbose_name='What is the estimated production of Ginger'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Estimated_Productiom_Tumeric',
            field=models.IntegerField(default=0, verbose_name='What is the estimated production of Tumeric'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='No_of_Bearing_Trees_Bayleaf',
            field=models.IntegerField(default=0, verbose_name='What is the number of Bearing trees for Bayleaf'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='No_of_Bearing_Trees_Cinnamon',
            field=models.IntegerField(default=0, verbose_name='What is the number of Bearing trees for Cinnamon'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='No_of_Bearing_Trees_Clove',
            field=models.IntegerField(default=0, verbose_name='What is the number of Bearing trees for clove'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='No_of_Bearing_Trees_Ginger',
            field=models.IntegerField(default=0, verbose_name='What is the number of Bearing trees for Ginger'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='No_of_Bearing_Trees_Tumeric',
            field=models.IntegerField(default=0, verbose_name='What is the number of Bearing trees for Tumeric'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='No_of_Non_Bearing_Trees_Bayleaf',
            field=models.IntegerField(default=0, verbose_name='What is the number of Non-Bearing trees for Bayleaf'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='No_of_Non_Bearing_Trees_Cinnamon',
            field=models.IntegerField(default=0, verbose_name='What is the number of Non-Bearing trees for Cinnamon'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='No_of_Non_Bearing_Trees_Clove',
            field=models.IntegerField(default=0, verbose_name='What is the number of Non-Bearing trees for clove'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='No_of_Non_Bearing_Trees_Ginger',
            field=models.IntegerField(default=0, verbose_name='What is the number of Non-Bearing trees for Ginger'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='No_of_Non_Bearing_Trees_Tumeric',
            field=models.IntegerField(default=0, verbose_name='What is the number of Non-Bearing trees for Tumeric'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Presence_of_Disease_Bayleaf',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Bayleaf'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Presence_of_Disease_Cinnamon',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Cinnamon'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Presence_of_Disease_Clove',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Clove'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Presence_of_Disease_Ginger',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Ginger'),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Presence_of_Disease_Tumeric',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Tumeric'),
        ),
    ]
