# Generated by Django 4.2.1 on 2023-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0033_alter_citrus_mango_trees_cultivation_lemon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land_info',
            name='Nutmeg_ID_No',
        ),
        migrations.AddField(
            model_name='land_tenur',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='Drains',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Good'), ('N', 'Fair'), ('N', 'Poor')], default='P', max_length=1, verbose_name='What is the state of the drains Drains'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='Fertilizing',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Good'), ('N', 'Fair'), ('N', 'Poor')], default='P', max_length=1, verbose_name='What is the state of the Fertilizing'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='Harvesting',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Good'), ('N', 'Fair'), ('N', 'Poor')], default='P', max_length=1, verbose_name='What is the state of the Harvesting'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='Land_Clearing',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Good'), ('N', 'Fair'), ('N', 'Poor')], default='P', max_length=1, verbose_name='What is the state of the Land_Clearing'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='Planting',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Good'), ('N', 'Fair'), ('N', 'Poor')], default='P', max_length=1, verbose_name='What is the state of the Planting'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='Presence_of_pest_and_diseases_on_nutmegs',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Good'), ('N', 'Fair'), ('N', 'Poor')], default='P', max_length=1, verbose_name='What is the state of pests and diseases?'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='Pruning',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Good'), ('N', 'Fair'), ('N', 'Poor')], default='P', max_length=1, verbose_name='What is the state of the Pruning'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='Weeds',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Good'), ('N', 'Fair'), ('N', 'Poor')], default='P', max_length=1, verbose_name='What is the state of the weeds?'),
        ),
        migrations.AlterField(
            model_name='food_safety_and_quality',
            name='Composed_manure',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1, verbose_name='Is composed manure used?'),
        ),
        migrations.AlterField(
            model_name='food_safety_and_quality',
            name='Fertilizer',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1, verbose_name='Is fertilizer used?'),
        ),
        migrations.AlterField(
            model_name='food_safety_and_quality',
            name='Raw_Manure',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1, verbose_name='Is raw manure used?'),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='Tree_types',
            field=models.CharField(choices=[('', '--Select an option--'), ('Nutmeg', 'Nutmeg'), ('Coconut', 'Coconut')], default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='land_elevation',
            field=models.CharField(choices=[('', '--Select an option--'), ('Low Belt', 'Low Belt'), ('Middle Belt', 'Middle Belt'), ('High Belt', 'High Belt')], default='P', max_length=100),
        ),
        migrations.AlterField(
            model_name='fullform',
            name='soil_type',
            field=models.CharField(choices=[('', '--Select an option--'), ('Sandy Soil', 'Sandy Soil'), ('Clay Soil', 'Clay Soil'), ('Stilt Soil', 'Stilt Soil'), ('Peat Soil', 'Peat Soil'), ('Chalk Soil', 'Chalk Soil'), ('Loamy Soil', 'Loamy Soil'), ('Clay Loam Soil', 'Clay Loam Soil'), ('Sandy Loam Soil', 'Sandy Loam Soil')], default='P', max_length=100),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='land_elevation',
            field=models.CharField(choices=[('', '--Select an option--'), ('Low Belt', 'Low Belt'), ('Middle Belt', 'Middle Belt'), ('High Belt', 'High Belt')], default='Select', max_length=100),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='rainfall_pattern',
            field=models.CharField(choices=[('', '--Select an option--'), ('Persistent', 'Persistent'), ('Occasional', 'Occasional'), ('Mild', 'Mild')], default='P', max_length=100),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='soil_type',
            field=models.CharField(choices=[('', '--Select an option--'), ('Sandy Soil', 'Sandy Soil'), ('Clay Soil', 'Clay Soil'), ('Stilt Soil', 'Stilt Soil'), ('Loamy Soil', 'Loamy Soil'), ('Clay Loam Soil', 'Clay Loam Soil'), ('Sandy Loam Soil', 'Sandy Loam Soil')], default='P', max_length=100),
        ),
        migrations.AlterField(
            model_name='nutmeg_frequency',
            name='Frequency',
            field=models.CharField(choices=[('', '--Select an option--'), ('Regular', 'Regular'), ('Occasional', 'Occasional'), ('Never', 'Never')], default='P', max_length=100, verbose_name='Select the frequency that best corresponds with the farm.'),
        ),
        migrations.AlterField(
            model_name='nutmeg_land',
            name='farm_type',
            field=models.CharField(choices=[('', '--Select an option--'), ('Normal', 'Normal'), ('Seasonal', 'Seasonal'), ('Abandoned', 'Abandoned')], default='P', max_length=100, verbose_name='Select the land type that best corresponds with the farm.'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='Other',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='policy',
            name='Pesticides',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1, verbose_name='Was pesticides used?'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='Septic_Tanks',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1, verbose_name='Are septic tanks used? '),
        ),
        migrations.AlterField(
            model_name='potential_risks',
            name='Chemical_Spills',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1, verbose_name='Are chemical Spills present?'),
        ),
        migrations.AlterField(
            model_name='potential_risks',
            name='Dumping_of_trash',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1, verbose_name='Did the dumping of trash occur recently?'),
        ),
        migrations.AlterField(
            model_name='potential_risks',
            name='Feedlot',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1, verbose_name='Is a feedlot Present?'),
        ),
        migrations.AlterField(
            model_name='potential_risks',
            name='Flooding',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1, verbose_name='Did flooding occur recently?'),
        ),
        migrations.AlterField(
            model_name='potential_risks',
            name='Heavy_Metal',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1, verbose_name='Are Heavy Metals present?'),
        ),
        migrations.AlterField(
            model_name='potential_risks',
            name='Slides',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1, verbose_name='Did land slides occur recently?'),
        ),
        migrations.AlterField(
            model_name='road_access',
            name='Road_Access',
            field=models.CharField(choices=[('', '--Select an option--'), ('Y', 'Yes'), ('N', 'No')], default='P', max_length=1, verbose_name='Is road access available?'),
        ),
    ]
