# Generated by Django 4.2.1 on 2023-06-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0034_remove_land_info_nutmeg_id_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land_info',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
