# Generated by Django 4.2.1 on 2023-06-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0036_citrus_mango_trees_nutmeg_id_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm_water_source',
            old_name='Haevested_Rain_Water',
            new_name='Harvested_Rain_Water',
        ),
    ]
