# Generated by Django 4.2.1 on 2023-06-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0037_rename_haevested_rain_water_farm_water_source_harvested_rain_water'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farmer_ID',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='other_crops',
        ),
        migrations.RemoveField(
            model_name='land_tenurship',
            name='farmer_ID',
        ),
        migrations.DeleteModel(
            name='Moisture_Analysis_A',
        ),
        migrations.RemoveField(
            model_name='state',
            name='farmer_ID',
        ),
        migrations.RemoveField(
            model_name='symmary',
            name='farmer_ID',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='farmer_ID',
        ),
        migrations.AddField(
            model_name='dried_moisture_analysis_a',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dried_moisture_analysis_b',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='floated_moisture_analysis_a',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='floated_moisture_analysis_b',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='farm',
        ),
        migrations.DeleteModel(
            name='Land_tenurship',
        ),
        migrations.DeleteModel(
            name='state',
        ),
        migrations.DeleteModel(
            name='symmary',
        ),
        migrations.DeleteModel(
            name='tree',
        ),
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
