# Generated by Django 4.2.1 on 2023-06-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0038_remove_farm_farmer_id_remove_farm_other_crops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citrus_mango_trees',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coconut_trees',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='farm_house',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='farm_water_source',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='farmer_info',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='food_safety_and_quality',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inspector_symmary',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='land_info',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='land_tenur',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nutmeg_frequency',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nutmeg_land',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nutmeg_trees',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nutmeg_variety',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='other_crops',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='other_crops_cultivated',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='other_seasoning_trees',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='other_spices_trees',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='potential_risks',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='road_access',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
