# Generated by Django 4.2.1 on 2023-06-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0043_cracking_summary_dispatch_of_dried_nutmeg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='BATCH_NUMBER',
            field=models.CharField(max_length=50, null=True, verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='STATION',
            field=models.CharField(choices=[('', '--Select Location--'), ('G', 'Grenville'), ('H', 'Hermitage'), ('M', 'Marli'), ('U', 'Union'), ('GP', 'Gouyave')], max_length=50, null=True, verbose_name='Station'),
        ),
    ]
