# Generated by Django 4.2.1 on 2023-06-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0044_alter_dispatch_of_dried_nutmeg_batch_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floation_summary',
            old_name='Ground_Floor',
            new_name='Ground_Floorh',
        ),
        migrations.RenameField(
            model_name='floation_summary',
            old_name='Shelf',
            new_name='Shelfh',
        ),
        migrations.RenameField(
            model_name='floation_summary',
            old_name='Tray',
            new_name='Trayh',
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='Ground_Floorl',
            field=models.CharField(max_length=50, null=True, verbose_name='Ground Floor'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='Shelfl',
            field=models.CharField(max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='Trayl',
            field=models.CharField(max_length=50, null=True, verbose_name='Tray'),
        ),
    ]
