# Generated by Django 4.2.1 on 2023-07-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0045_rename_ground_floor_floation_summary_ground_floorh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_house_drying',
            name='ALERT',
            field=models.CharField(default='A', max_length=50, verbose_name='Alert'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='LOCATION3',
            field=models.CharField(choices=[('', '--Select Location--'), ('Ground Floor', 'Ground Floor'), ('1st Floor', '1st Floor'), ('2nd Floor', '2nd Floor'), ('Loft', 'Loft')], max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='PREDOMINANT_DEFECT',
            field=models.CharField(choices=[('', '--Select Location--'), ('Cracked', 'Cracked'), ('Grow Heads', 'Grow Heads'), ('Lights', 'Lights'), ('Mould', 'Mould')], max_length=50, verbose_name='Predominant Defect'),
        ),
    ]
