# Generated by Django 4.2.1 on 2023-07-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0047_cracking_summary_nutmeg_id_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cracking_summary',
            name='Nutmeg_ID_No',
        ),
        migrations.RemoveField(
            model_name='cracking_summary',
            name='Worker_ID_No',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Nutmeg_ID_No',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Worker_ID_No',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_green_nutmeg',
            name='Nutmeg_ID_No',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_green_nutmeg',
            name='Worker_ID_No',
        ),
        migrations.RemoveField(
            model_name='floation_summary',
            name='Nutmeg_ID_No',
        ),
        migrations.RemoveField(
            model_name='floation_summary',
            name='Worker_ID_No',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Nutmeg_ID_No',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Worker_ID_No',
        ),
        migrations.RemoveField(
            model_name='package_ciontrol',
            name='Nutmeg_ID_No',
        ),
        migrations.RemoveField(
            model_name='package_ciontrol',
            name='Worker_ID_No',
        ),
    ]
