# Generated by Django 4.2.1 on 2023-07-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0050_alter_in_house_drying_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Worker_ID_No',
        ),
    ]
