# Generated by Django 4.2.1 on 2023-07-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0052_remove_in_house_drying_nutmeg_id_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_house_drying',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
