# Generated by Django 4.2.1 on 2023-07-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0053_in_house_drying_nutmeg_id_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cracking_summary',
            name='Worker_ID_No',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Worker_ID_No',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_green_nutmeg',
            name='Worker_ID_No',
        ),
        migrations.RemoveField(
            model_name='floation_summary',
            name='Worker_ID_No',
        ),
        migrations.RemoveField(
            model_name='package_ciontrol',
            name='Worker_ID_No',
        ),
    ]
