# Generated by Django 4.2.1 on 2023-07-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0054_remove_cracking_summary_worker_id_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Floor_1st_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Floor_1st_2',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Floor_2nd_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Floor_2nd_2',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Floor_Loft_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Floor_Loft_2',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Ground_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Ground_2',
        ),
        migrations.RemoveField(
            model_name='floation_summary',
            name='Ground_Floorh',
        ),
        migrations.RemoveField(
            model_name='floation_summary',
            name='Ground_Floorl',
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Floor_1st_1',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Floor_1st_2',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Floor_2nd_1',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Floor_2nd_2',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Floor_Loft_1',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Floor_Loft_2',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Ground_1',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Ground_2',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Floor_1st_1',
            field=models.CharField(choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Floor_1st_2',
            field=models.CharField(choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Floor_2nd_1',
            field=models.CharField(choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Floor_2nd_2',
            field=models.CharField(choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Floor_Loft_1',
            field=models.CharField(choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Floor_Loft_2',
            field=models.CharField(choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Ground_1',
            field=models.CharField(choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Ground_2',
            field=models.CharField(choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Floor_1st_1',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Floor_1st_2',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Floor_2nd_1',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Floor_2nd_2',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Floor_Loft_1',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Floor_Loft_2',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Ground_1',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Ground_2',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='Sectionh',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='Sectionl',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='Shelfh',
            field=models.CharField(choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='Shelfl',
            field=models.CharField(choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='Trayh',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='Trayl',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
    ]
