# Generated by Django 4.2.1 on 2023-07-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0055_remove_dispatch_of_dried_nutmeg_floor_1st_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Floor_1st_1',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Floor_2nd_1',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Floor_Loft_1',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Ground_1',
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='Section_Ground_1',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='Shelf_Ground_1',
            field=models.CharField(choices=[('', '--Select shelf--'), ('A', 'B'), ('B', 'A'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='Tray_Ground_1',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
    ]
