# Generated by Django 4.2.1 on 2023-07-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0056_remove_in_house_drying_floor_1st_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='in_house_drying',
            old_name='Section_Ground_1',
            new_name='SectionG',
        ),
        migrations.RenameField(
            model_name='in_house_drying',
            old_name='Tray_Ground_1',
            new_name='TrayG',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Floor_1st_2',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Floor_2nd_2',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Floor_Loft_2',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Ground_2',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Shelf_Ground_1',
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='SectionGP',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='SectionGP_0',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='SectionG_0',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='SectionH',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='SectionH_0',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='SectionM',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='SectionM_0',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='SectionU',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='SectionU_0',
            field=models.CharField(choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='ShelfG',
            field=models.CharField(choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='ShelfGP',
            field=models.CharField(choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='ShelfGP_0',
            field=models.CharField(choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='ShelfG_0',
            field=models.CharField(choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='ShelfH',
            field=models.CharField(choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='ShelfH_0',
            field=models.CharField(choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='ShelfM',
            field=models.CharField(choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='ShelfM_0',
            field=models.CharField(choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='ShelfU',
            field=models.CharField(choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='ShelfU_0',
            field=models.CharField(choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='TrayGP',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='TrayGP_0',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='TrayG_0',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='TrayH',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='TrayH_0',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='TrayM',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='TrayM_0',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='TrayU',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='TrayU_0',
            field=models.CharField(choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
    ]
