# Generated by Django 4.2.1 on 2023-07-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0061_alter_in_house_drying_sectiongp_0_1f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_house_drying',
            name='Nutmeg_ID_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
