# Generated by Django 4.2.1 on 2023-08-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0062_alter_in_house_drying_nutmeg_id_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='dried_moisture_analysis_a',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dried_moisture_analysis_b',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='floated_moisture_analysis_a',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='floated_moisture_analysis_b',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
