# Generated by Django 4.2.1 on 2023-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0063_dried_moisture_analysis_a_worker_id_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='Final_Sample_Weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='Final_Sample_Weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='Final_Sample_Weight_H',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='Final_Sample_Weight_L',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='Initial_Sample_Weight_H',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='Initial_Sample_Weight_L',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
