# Generated by Django 4.2.1 on 2023-08-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0064_alter_dried_moisture_analysis_a_final_sample_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Floor_1st_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Floor_1st_2',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Floor_2nd_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Floor_2nd_2',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Floor_Loft_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Floor_Loft_2',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Ground_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section_Ground_2',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Floor_1st_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Floor_1st_2',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Floor_2nd_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Floor_2nd_2',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Floor_Loft_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Floor_Loft_2',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Ground_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf_Ground_2',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Floor_1st_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Floor_1st_2',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Floor_2nd_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Floor_2nd_2',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Floor_Loft_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Floor_Loft_2',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Ground_1',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray_Ground_2',
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionG',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionGP_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionGP_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionGP_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionGP_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionG_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionG_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionG_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionG_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionH_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionH_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionH_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionH_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionM',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionM_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionM_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionM_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionM_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionU_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionU_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionU_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionU_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Shelf',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfG',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfGP_1F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfGP_2F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfGP_FL',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfGP_GF',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfG_1F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfG_2F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfG_FL',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfG_GF',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfH_1F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfH_2F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfH_FL',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfH_GF',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfM_1F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfM_2F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfM_FL',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfM_GF',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfU_1F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfU_2F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfU_FL',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='ShelfU_GF',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Tray',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayG',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayGP_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayGP_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayGP_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayGP_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayG_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayG_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayG_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayG_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayH_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayH_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayH_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayH_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayM_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayM_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayM_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayM_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayU_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayU_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayU_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='TrayU_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
    ]
