# Generated by Django 4.2.1 on 2023-08-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0065_remove_dispatch_of_dried_nutmeg_section_floor_1st_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureGP_1F',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureGP_2F',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureGP_FL',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureGP_GF',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureG_1F',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureG_2F',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureG_FL',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureG_GF',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureH_1F',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureH_2F',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureH_FL',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureH_GF',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureM_1F',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureM_2F',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureM_FL',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureM_GF',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureU_1F',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureU_2F',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureU_FL',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureU_GF',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='MoisturGPe_heavy',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='MoistureGP_light',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='MoistureG_heavy',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='MoistureG_light',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='MoistureH_heavy',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='MoistureH_light',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='MoistureM_heavy',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='MoistureM_light',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='MoistureU_heavy',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='MoistureU_light',
            field=models.CharField(max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='SectionGP_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='SectionGP_light',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='SectionG_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='SectionG_light',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='SectionH_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='SectionH_light',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='SectionM_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='SectionM_light',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='SectionU_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='SectionU_light',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='ShelfGP_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='ShelfGP_light',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='ShelfG_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='ShelfG_light',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='ShelfH_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='ShelfH_light',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='ShelfM_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='ShelfM_light',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='ShelfU_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='ShelfU_light',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('1', '1'), ('2', '2')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='TrayGP_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='TrayGP_light',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='TrayG_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='TrayG_light',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='TrayH_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='TrayH_light',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='TrayM_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='TrayM_light',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='TrayU_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='TrayU_light',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Tray'),
        ),
    ]
