# Generated by Django 4.2.1 on 2023-08-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0066_dispatch_of_dried_nutmeg_moisturegp_1f_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floation_summary',
            name='FINAL_MOISTURE_H',
        ),
        migrations.RemoveField(
            model_name='floation_summary',
            name='FINAL_MOISTURE_L',
        ),
        migrations.RemoveField(
            model_name='floation_summary',
            name='MoisturGPe_heavy',
        ),
        migrations.RemoveField(
            model_name='floation_summary',
            name='Sectionh',
        ),
        migrations.RemoveField(
            model_name='floation_summary',
            name='Sectionl',
        ),
        migrations.RemoveField(
            model_name='floation_summary',
            name='Shelfh',
        ),
        migrations.RemoveField(
            model_name='floation_summary',
            name='Shelfl',
        ),
        migrations.RemoveField(
            model_name='floation_summary',
            name='Trayh',
        ),
        migrations.RemoveField(
            model_name='floation_summary',
            name='Trayl',
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='MoistureGP_heavy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='MoistureGP_light',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='MoistureG_heavy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='MoistureG_light',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='MoistureH_heavy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='MoistureH_light',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='MoistureM_heavy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='MoistureM_light',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='MoistureU_heavy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='MoistureU_light',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionGP_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionGP_light',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionG_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionG_light',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionH_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionH_light',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionM_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionM_light',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionU_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionU_light',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='ShelfGP_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='ShelfGP_light',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='ShelfG_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='ShelfG_light',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='ShelfH_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='ShelfH_light',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='ShelfM_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='ShelfM_light',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='ShelfU_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='ShelfU_light',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='TrayGP_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='TrayGP_light',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='TrayG_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='TrayG_light',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='TrayH_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='TrayH_light',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='TrayM_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='TrayM_light',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='TrayU_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='TrayU_light',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
    ]
