# Generated by Django 4.2.1 on 2023-08-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0067_remove_floation_summary_final_moisture_h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureGP_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureGP_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureGP_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureGP_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureG_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureG_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureG_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureG_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureH_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureH_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureH_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureH_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureM_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureM_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureM_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureM_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureU_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureU_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureU_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='MoistureU_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Station'),
        ),
    ]
