# Generated by Django 4.2.1 on 2023-08-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0068_alter_dispatch_of_dried_nutmeg_moisturegp_1f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land_info',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
