# Generated by Django 4.2.1 on 2023-08-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0069_alter_land_info_nutmeg_id_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land_info',
            name='Cultivation_Atlantic_Tall',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the Atlantic Tall Tree cultivation'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='Cultivation_Dwarf',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state of the Dwarf Tree cultivation'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='End_Use_Atlantic_Tall',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the intended end use if the Atlantic Tall Tree'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='End_Use_Dwarf',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the intended end use of the Dwarf Tree'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='Estimated_Productiom_Atlantic_Tall',
            field=models.IntegerField(default=0, verbose_name='What is the estimated production of Atlantic Tall Trees'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='Estimated_Productiom_Dwarf',
            field=models.IntegerField(default=0, verbose_name='What is the estimated production of Dwarf Trees'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='No_of_Bearing_Trees_Atlantic_Tall',
            field=models.IntegerField(default=0, verbose_name='What is the number of Bearing trees for Atlantic Tall Trees'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='No_of_Bearing_Trees_Dwarf',
            field=models.IntegerField(default=0, verbose_name='What is the number of Bearing trees for Dwarf Trees'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='No_of_Non_Bearing_Trees_Atlantic_Tall',
            field=models.IntegerField(default=0, verbose_name='What is the number of Non-Bearing trees for Atlantic Tall Trees'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='No_of_Non_Bearing_Trees_Dwarf',
            field=models.IntegerField(default=0, verbose_name='What is the number of Non-Bearing Dwarf Trees'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='Presence_of_Disease_Atlantic_Tall',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Atlantic Tall Trees'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='Presence_of_Disease_Dwarf',
            field=models.CharField(max_length=50, null=True, verbose_name='What is the state disease for Dwarf Trees'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='acreage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='land_info',
            name='farm_type',
            field=models.CharField(choices=[('', '--Select an option--'), ('Nutmeg', 'Nutmeg'), ('Coconut', 'Coconut')], default='P', max_length=100),
        ),
        migrations.AddField(
            model_name='land_info',
            name='insurance_zone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='land_info',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='land_info',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='land_info',
            name='parish',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='land_info',
            name='village',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
