# Generated by Django 4.2.1 on 2023-08-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0070_land_info_cultivation_atlantic_tall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land_info',
            name='Bearing_trees_16_24_years',
            field=models.IntegerField(default=0, verbose_name='Estimated production Bearing trees between 16 to 24'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='Bearing_trees_16_24_years_quantity',
            field=models.IntegerField(default=0, verbose_name='Number of Bearing trees between 16 to 24'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='Bearing_trees_6_15_years_estimated_production',
            field=models.IntegerField(default=0, verbose_name='Estimated production Bearing trees between 6 to 14'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='Bearing_trees_6_15_years_quantity',
            field=models.IntegerField(default=0, verbose_name='Number of Bearing trees between 6 to 14'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='Estimated_peak_period',
            field=models.IntegerField(default=0, verbose_name='What is the estimated peak period?'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='Mature_trees_25_years_estimated_production',
            field=models.IntegerField(default=0, verbose_name='Estimated production for Mature older than 25 years'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='Mature_trees_25_years_quantity',
            field=models.IntegerField(default=0, verbose_name='Number of Mature trees older than 25 years'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='Non_Bearing_trees_5_years_estimated_production',
            field=models.IntegerField(default=0, verbose_name='Estimated production for Non-bearing trees younger than 5 years'),
        ),
        migrations.AddField(
            model_name='land_info',
            name='Non_Bearing_trees_5_years_quantity',
            field=models.IntegerField(default=0, verbose_name='Number of Non-Bearing trees younger than 5 years'),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='Cultivation_Atlantic_Tall',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='What is the state of the Atlantic Tall Tree cultivation'),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='Cultivation_Dwarf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='What is the state of the Dwarf Tree cultivation'),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='End_Use_Atlantic_Tall',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='What is the intended end use if the Atlantic Tall Tree'),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='End_Use_Dwarf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='What is the intended end use of the Dwarf Tree'),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='Estimated_Productiom_Atlantic_Tall',
            field=models.IntegerField(blank=True, default=0, verbose_name='What is the estimated production of Atlantic Tall Trees'),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='Estimated_Productiom_Dwarf',
            field=models.IntegerField(blank=True, default=0, verbose_name='What is the estimated production of Dwarf Trees'),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='No_of_Bearing_Trees_Atlantic_Tall',
            field=models.IntegerField(blank=True, default=0, verbose_name='What is the number of Bearing trees for Atlantic Tall Trees'),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='No_of_Bearing_Trees_Dwarf',
            field=models.IntegerField(blank=True, default=0, verbose_name='What is the number of Bearing trees for Dwarf Trees'),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='No_of_Non_Bearing_Trees_Atlantic_Tall',
            field=models.IntegerField(blank=True, default=0, verbose_name='What is the number of Non-Bearing trees for Atlantic Tall Trees'),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='No_of_Non_Bearing_Trees_Dwarf',
            field=models.IntegerField(blank=True, default=0, verbose_name='What is the number of Non-Bearing Dwarf Trees'),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='Presence_of_Disease_Atlantic_Tall',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='What is the state disease for Atlantic Tall Trees'),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='Presence_of_Disease_Dwarf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='What is the state disease for Dwarf Trees'),
        ),
    ]
