# Generated by Django 4.2.1 on 2023-08-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0074_alter_citrus_mango_trees_nutmeg_id_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land_info',
            name='tenurship',
            field=models.CharField(choices=[('', '--Select an option--'), ('Owned', 'Owned'), ('Freehold', 'Freehold'), ('Leased', 'Leased'), ('Family Land', 'Family Land'), ('ShareCrop', 'ShareCrop'), ('Rent', 'Rent'), ('Rented free', 'Rented free'), ('Premission to work land', 'Premission to work land'), ('Squatted', 'Squatted'), ('Government Land', 'Government Land'), ('Other', 'Other'), ('Caretaker', 'Caretaker'), ('Administrator', 'Administrator')], max_length=100, null=True),
        ),
    ]
