# Generated by Django 4.2.1 on 2023-08-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0075_land_info_tenurship'),
    ]

    operations = [
        migrations.AddField(
            model_name='land_info',
            name='training',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
