# Generated by Django 4.2.1 on 2023-08-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0076_land_info_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='land_info',
            name='visit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
