# Generated by Django 4.2.1 on 2023-08-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0081_land_tenur_farm_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labour_support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worker_ID_No', models.CharField(max_length=50, null=True)),
                ('Nutmeg_ID_No', models.CharField(max_length=50, null=True)),
                ('Type_of_Assistance', models.CharField(choices=[('', '--Select an option--'), ('Low Belt', 'GCNA Farm Loan'), ('Middle Belt', 'GCNA Farm Assistance Program'), ('High Belt', 'MOA Farm Assistance Program'), ('Low Belt', 'MOA ADAP Program'), ('Middle Belt', 'GCNA Farm Loan'), ('High Belt', 'GCNA Assitance Program'), ('Low Belt', 'Grenada Development Bank Project'), ('Middle Belt', 'Bank Loan'), ('High Belt', 'Grant Fund'), ('High Belt', 'Other')], default='A', max_length=50)),
                ('Date_Recieved', models.DateField(default='A', max_length=50)),
                ('Nature_of_Assistance', models.CharField(choices=[('', '--Select an option--'), ('Low Belt', 'Land Clearing'), ('Middle Belt', 'Drainage'), ('High Belt', 'Weed Control'), ('Low Belt', 'Fertilizing'), ('Middle Belt', 'Pruning'), ('High Belt', 'Harvesting'), ('Low Belt', 'Planting/transplanting'), ('Middle Belt', 'Pest/Disease'), ('High Belt', 'Management')], default='A', max_length=50)),
                ('Objective_of_the_Assistance', models.CharField(choices=[('', '--Select an option--'), ('Low Belt', 'Land Clearing'), ('Middle Belt', 'Drainage'), ('High Belt', 'Weed Control'), ('Low Belt', 'Fertilizing'), ('Middle Belt', 'Pruning'), ('High Belt', 'Harvesting'), ('Low Belt', 'Planting/transplanting'), ('Middle Belt', 'Pest/Disease'), ('High Belt', 'Management')], default='A', max_length=50)),
                ('Facilitator_of_the_Assistance', models.CharField(choices=[('', '--Select an option--'), ('Low Belt', 'Procurments of Farm inputs to increase farm productivity'), ('Middle Belt', 'Farm labour support to increase production'), ('High Belt', 'Other')], default='A', max_length=50)),
                ('Facilitator_of_the_Assistance_cont', models.CharField(choices=[('', '--Select an option--'), ('Low Belt', 'Ministry of Agriculture(MOA)- World Bank'), ('Grenada Development(GDB)', 'Grenada Development(GDB)'), ('GEF', 'GEF'), ('GIDC', 'GIDC'), ('GCNA', 'GCNA'), ('GCA', 'GCA'), ('Other', 'Other')], default='A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Training_support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worker_ID_No', models.CharField(max_length=50, null=True)),
                ('Nutmeg_ID_No', models.CharField(max_length=50, null=True)),
                ('Type_of_Training', models.CharField(choices=[('', '--Select an option--'), ('Low Belt', 'GAP'), ('Middle Belt', 'GMP'), ('High Belt', 'HACCP'), ('Low Belt', 'Use of small farming tools and equipment'), ('Middle Belt', 'Land Use'), ('High Belt', 'Pest and Disease'), ('Low Belt', 'Management'), ('Middle Belt', 'Post Harvesting Handling'), ('High Belt', 'Harvesting'), ('Low Belt', 'Grafting'), ('Middle Belt', 'Farm Management'), ('High Belt', 'Other')], default='A', max_length=50)),
                ('Type_of_Training_cont', models.CharField(default='A', max_length=50)),
                ('Date_Recieved', models.DateField(default='A', max_length=50)),
                ('Objective_of_the_Training', models.CharField(choices=[('', '--Select an option--'), ('Low Belt', 'Increase farm productivity2'), ('Middle Belt', 'Improve the quality of produce'), ('High Belt', 'Technical Knowledge'), ('Low Belt', 'Increase from production'), ('Middle Belt', 'Improve harvesting'), ('High Belt', 'Farm Buisness Management'), ('Low Belt', 'Improve the quality of plants'), ('Middle Belt', 'Other')], default='A', max_length=50)),
                ('Objective_of_the_Training_cont', models.CharField(default='A', max_length=50)),
                ('Facilitator_of_the_Training', models.CharField(choices=[('', '--Select an option--'), ('Low Belt', 'GCNA'), ('Middle Belt', 'GCA'), ('High Belt', 'MOA'), ('Low Belt', 'GIDC'), ('Middle Belt', 'Bureau of Standards'), ('High Belt', 'UNDP/SAEP'), ('Low Belt', 'Other')], default='A', max_length=50)),
                ('Facilitator_of_the_Training_cont', models.CharField(default='A', max_length=50)),
            ],
        ),
    ]
