# Generated by Django 4.2.1 on 2023-08-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0083_alter_labour_support_date_recieved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coconut_trees',
            name='tenurship',
            field=models.CharField(choices=[('', '--Select an option--'), ('Owned', 'Owned'), ('Freehold', 'Freehold'), ('Leased', 'Leased'), ('Family Land', 'Family Land'), ('ShareCrop', 'ShareCrop'), ('Rent', 'Rent'), ('Rented free', 'Rented free'), ('Premission to work land', 'Premission to work land'), ('Squatted', 'Squatted'), ('Government Land', 'Government Land'), ('Caretaker', 'Caretaker'), ('Administrator', 'Administrator'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labour_support',
            name='Facilitator_of_the_Assistance',
            field=models.CharField(blank=True, choices=[('', '--Select an option--'), ('Ministry of Agriculture(MOA)- World Bank', 'Ministry of Agriculture(MOA)- World Bank'), ('Grenada Development(GDB)', 'Grenada Development(GDB)'), ('GEF', 'GEF'), ('GIDC', 'GIDC'), ('GCNA', 'GCNA'), ('GCA', 'GCA'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labour_support',
            name='Nature_of_Assistance',
            field=models.CharField(blank=True, choices=[('', '--Select an option--'), ('Land Clearing', 'Land Clearing'), ('Drainage', 'Drainage'), ('Weed Control', 'Weed Control'), ('Fertilizing', 'Fertilizing'), ('Pruning', 'Pruning'), ('Harvesting', 'Harvesting'), ('Planting/transplanting', 'Planting/transplanting'), ('Pest/Disease', 'Pest/Disease'), ('Management', 'Management')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labour_support',
            name='Objective_of_the_Assistance',
            field=models.CharField(blank=True, choices=[('', '--Select an option--'), ('Procurments of Farm inputs to increase farm productivity', 'Procurments of Farm inputs to increase farm productivity'), ('Farm labour support to increase production', 'Farm labour support to increase production'), ('Other', 'Other')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='labour_support',
            name='Type_of_Assistance',
            field=models.CharField(blank=True, choices=[('', '--Select an option--'), ('GCNA Farm Loan', 'GCNA Farm Loan'), ('GCNA Farm Assistance Program', 'GCNA Farm Assistance Program'), ('MOA Farm Assistance Program', 'MOA Farm Assistance Program'), ('MOA ADAP Program', 'MOA ADAP Program'), ('GCNA Farm Loan', 'GCNA Farm Loan'), ('GCNA Assitance Program', 'GCNA Assitance Program'), ('Grenada Development Bank Project', 'Grenada Development Bank Project'), ('Bank Loan', 'Bank Loan'), ('Grant Fund', 'Grant Fund'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='training_support',
            name='Facilitator_of_the_Training',
            field=models.CharField(choices=[('', '--Select an option--'), ('GCNA', 'GCNA'), ('GCA', 'GCA'), ('MOA', 'MOA'), ('GIDC', 'GIDC'), ('Bureau of Standards', 'Bureau of Standards'), ('UNDP/SAEP', 'UNDP/SAEP'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='training_support',
            name='Objective_of_the_Training',
            field=models.CharField(choices=[('', '--Select an option--'), ('Increase farm productivity', 'Increase farm productivity'), ('Improve the quality of produce', 'Improve the quality of produce'), ('Technical Knowledge', 'Technical Knowledge'), ('Increase from production', 'Increase from production'), ('Improve harvesting', 'Improve harvesting'), ('Farm Buisness Management', 'Farm Buisness Management'), ('Improve the quality of plants', 'Improve the quality of plants'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='training_support',
            name='Type_of_Training',
            field=models.CharField(choices=[('', '--Select an option--'), ('GAP', 'GAP'), ('GMP', 'GMP'), ('HACCP', 'HACCP'), ('Use of small farming tools and equipment', 'Use of small farming tools and equipment'), ('Land Use', 'Land Use'), ('Pest and Disease', 'Pest and Disease'), ('Management', 'Management'), ('Post Harvesting Handling', 'Post Harvesting Handling'), ('Harvesting', 'Harvesting'), ('Grafting', 'Grafting'), ('Farm Management', 'Farm Management'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
