# Generated by Django 4.2.1 on 2023-08-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0084_alter_coconut_trees_tenurship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land_tenur',
            name='visit',
        ),
    ]
