# Generated by Django 4.2.1 on 2023-08-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0085_remove_land_tenur_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worker_ID_No', models.CharField(max_length=50, null=True)),
                ('Nutmeg_ID_No', models.CharField(max_length=50, null=True)),
                ('purpose_of_visit', models.CharField(max_length=50, null=True)),
                ('Date_of_visit', models.DateField(null=True, verbose_name='Visit Date')),
                ('parish', models.CharField(max_length=50, null=True)),
                ('training', models.CharField(max_length=50, null=True)),
                ('tenurship', models.CharField(choices=[('', '--Select an option--'), ('Owned', 'Owned'), ('Freehold', 'Freehold'), ('Leased', 'Leased'), ('Family Land', 'Family Land'), ('ShareCrop', 'ShareCrop'), ('Rent', 'Rent'), ('Rented free', 'Rented free'), ('Premission to work land', 'Premission to work land'), ('Squatted', 'Squatted'), ('Government Land', 'Government Land'), ('Other', 'Other'), ('Caretaker', 'Caretaker'), ('Administrator', 'Administrator')], max_length=100, null=True)),
                ('visit', models.CharField(max_length=50, null=True)),
                ('village', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
