# Generated by Django 4.2.1 on 2023-09-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0086_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dried_moisture_analysis_b',
            old_name='SIGNED_BY',
            new_name='APPROVED_BY',
        ),
    ]
