# Generated by Django 4.2.1 on 2023-09-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0087_rename_signed_by_dried_moisture_analysis_b_approved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dried_moisture_analysis_a',
            old_name='SIGNED_BY',
            new_name='APPROVED_BY',
        ),
    ]
