# Generated by Django 4.2.1 on 2023-09-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0088_rename_signed_by_dried_moisture_analysis_a_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='floated_moisture_analysis_a',
            name='BATCH_CODE',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='DECISION',
            field=models.CharField(choices=[('', 'What was the decision made?'), ('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='DECISION',
            field=models.CharField(choices=[('', 'What was the decision made?'), ('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=50, null=True),
        ),
    ]
