# Generated by Django 4.2.1 on 2023-09-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0089_floated_moisture_analysis_a_batch_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='AVERAGE_L',
            field=models.DecimalField(choices=[('', 'What was the decision made?'), ('PASS', 'Pass'), ('FAIL', 'Fail')], decimal_places=2, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='DECISION_H',
            field=models.CharField(choices=[('', 'What was the decision made?'), ('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=50, null=True),
        ),
    ]
