# Generated by Django 4.2.1 on 2023-09-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0090_alter_floated_moisture_analysis_a_average_l_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floated_moisture_analysis_a',
            old_name='SIGNED_BY',
            new_name='Approved_BY',
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='AVERAGE_L',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='DECISION_L',
            field=models.CharField(choices=[('', 'What was the decision made?'), ('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=50, null=True),
        ),
    ]
