# Generated by Django 4.2.1 on 2023-09-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0092_floated_moisture_analysis_b_total_weight_h_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quality_control',
            old_name='ASSORTOR',
            new_name='ASSORTOR1',
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR1_A',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR1_B',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR1_C',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR1_D',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR1_E',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR2_A',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR2_B',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR2_C',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR2_D',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR2_E',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR3_A',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR3_B',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR3_C',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR3_D',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR3_E',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR4_A',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR4_B',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR4_C',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR4_D',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR4_E',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR5_A',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR5_B',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR5_C',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR5_D',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR5_E',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
