# Generated by Django 4.2.1 on 2023-09-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0095_quality_control_supervisor_b_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quality_control',
            old_name='SIGNED_BY',
            new_name='Approved_BY',
        ),
    ]
