# Generated by Django 4.2.1 on 2023-09-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0096_rename_signed_by_quality_control_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer_info',
            name='acreage',
        ),
        migrations.RemoveField(
            model_name='farmer_info',
            name='insurance_zone',
        ),
        migrations.RemoveField(
            model_name='farmer_info',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='farmer_info',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='farmer_info',
            name='parish',
        ),
        migrations.RemoveField(
            model_name='farmer_info',
            name='village',
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureGP_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureGP_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureGP_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureGP_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureG_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureG_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureG_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureG_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureH_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureH_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureH_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureH_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureM_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureM_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureM_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureM_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureU_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureU_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureU_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='MoistureU_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightGP_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightGP_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightGP_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightGP_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightG_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightG_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightG_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightG_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightH_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightH_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightH_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightH_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightM_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightM_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightM_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightM_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightU_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightU_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightU_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='WeightU_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='package_ciontrol',
            name='Chemical_Analysis',
            field=models.CharField(choices=[('', '--Select Location--'), ('Jute', 'Jute'), ('Polypropylene', 'Polypropylene'), ('Other', 'Other')], default='A', max_length=50, verbose_name='Pakaging Material'),
        ),
        migrations.AddField(
            model_name='package_ciontrol',
            name='Microbiological_Analysis',
            field=models.CharField(choices=[('', '--Select Location--'), ('Jute', 'Jute'), ('Polypropylene', 'Polypropylene'), ('Other', 'Other')], default='A', max_length=50, verbose_name='Pakaging Material'),
        ),
        migrations.AddField(
            model_name='package_ciontrol',
            name='Physical_Analysis',
            field=models.CharField(choices=[('', '--Select Location--'), ('Jute', 'Jute'), ('Polypropylene', 'Polypropylene'), ('Other', 'Other')], default='A', max_length=50, verbose_name='Pakaging Material'),
        ),
    ]
