# Generated by Django 4.2.1 on 2023-09-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0097_remove_farmer_info_acreage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_house_drying',
            name='ALERT_cont',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alert'),
        ),
    ]
