# Generated by Django 4.2.1 on 2023-09-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0098_in_house_drying_alert_cont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_house_drying',
            name='ALERT',
            field=models.CharField(blank=True, choices=[('', 'Send Alert?'), ('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name='Alert'),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='STATION',
            field=models.CharField(choices=[('', 'Select Station'), ('Beaulieu', 'Beaulieu'), ('Gouyave', 'Gouyave'), ('Grenville', 'Grenville')], max_length=50, null=True),
        ),
    ]
