# Generated by Django 4.2.1 on 2023-09-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0100_quality_control_nutmeg_assorted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality_control',
            name='ASSORTOR6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='STATION',
            field=models.CharField(choices=[('', '--Select Location--'), ('G', 'Beaulieu'), ('GP', 'Gouyave')], max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='package_ciontrol',
            name='PRODUCT_DESCRIPTION',
            field=models.CharField(choices=[('', '--Select Description--'), ('SUNS', 'SUNS'), ('GROUND NUTMEG', 'GROUND NUTMEG'), ('CRACKED NUTMEG', 'CRACKED NUTMEG'), ('110’S', ' 110’S'), ('80’S', ' 80’S'), ('GUNS', 'GUNS'), ('MACE', 'MACE'), ('Others', 'Others')], default='A', max_length=50, verbose_name='Product Description'),
        ),
    ]
