# Generated by Django 4.2.1 on 2023-09-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0102_cracking_summary_control_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_ciontrol',
            name='Nutmeg_Assorted_cont',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='package_ciontrol',
            name='PACKAGING_MATERIAL_cont',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='package_ciontrol',
            name='PRODUCT_DESCRIPTION_cont',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
