# Generated by Django 4.2.1 on 2023-10-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0103_package_ciontrol_nutmeg_assorted_cont_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality_control',
            name='Nutmeg_Assorted_cont',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
