# Generated by Django 4.2.1 on 2023-10-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0104_quality_control_nutmeg_assorted_cont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dried_moisture_analysis_b',
            name='Additional_Drying_Period',
        ),
        migrations.AddField(
            model_name='dried_moisture_analysis_b',
            name='Additional_Drying_Period1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dried_moisture_analysis_b',
            name='Additional_Drying_Period2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dried_moisture_analysis_b',
            name='Additional_Drying_Period3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='Nutmeg_Assorted2',
            field=models.CharField(choices=[('', 'Select'), ('Sounds', 'Sounds'), ('Lights', 'Lights'), ("110's", "110's"), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
