# Generated by Django 4.2.1 on 2023-10-23 17:56

from django.db import migrations, models
import gcna_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0105_remove_dried_moisture_analysis_b_additional_drying_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land_info',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
    ]
