# Generated by Django 4.2.1 on 2023-10-31 17:31

from django.db import migrations, models
import gcna_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0106_land_info_land_id_n0'),
    ]

    operations = [
        migrations.AddField(
            model_name='citrus_mango_trees',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='coconut_trees',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='condition',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='farm_house',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='farm_water_source',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='food_safety_and_quality',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='inspector_symmary',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='land_tenur',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='nutmeg_frequency',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='nutmeg_land',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='nutmeg_trees',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='nutmeg_variety',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='other_crops',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='other_crops_cultivated',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='other_seasoning_trees',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='other_spices_trees',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='policy',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='potential_risks',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='road_access',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='training_support',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
    ]
