# Generated by Django 4.2.1 on 2023-10-31 17:54

from django.db import migrations, models
import gcna_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0107_citrus_mango_trees_land_id_n0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_support',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
    ]
